new = 'C:/Users/libwebadmin/findit_data/new/'
update = 'C:/Users/libwebadmin/findit_data/update/'
delete = 'C:/Users/libwebadmin/findit_data/delete/'
scripts_dir = 'C:/Users/libwebadmin/findit/ingest_scripts/'
solr_url = 'http://localhost:8983/solr/blacklight-core/'
